version: '3'
services:
    bot:
        container_name: clip-bot
        entrypoint: python bot --storage redis
        env_file:
            - ".env"
        build: ./
        depends_on:
            - redis-fsm-storage
        links:
            - redis-fsm-storage
  
    redis-fsm-storage:
        container_name: redis-fsm-storage
        image: redis
        ports:
            - '6380:6379'
        volumes:
            - redis-fsm-storage:/data
      

volumes:
    redis-fsm-storage:
