name: CI with tox
on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v1
      - name: Install tox
        run: pip install tox
      - name: Run black
        run: |
          tox -e black

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v1
      - name: Install tox
        run: pip install tox
      - name: Run flake8
        run: |
          tox -e flake8

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v1
      - name: Install tox
        run: pip install tox
      - name: Run pylint
        run: |
          tox -e pylint


  vulture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v1
      - name: Install tox
        run: pip install tox
      - name: Run vulture
        run: |
          tox -e vulture

  test:
    runs-on: ubuntu-latest
    needs: [black, flake8, pylint, vulture]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: PIP upgrade
        run: python -m pip install --upgrade pip
      - name: Install tox
        run: pip install tox
      - name: Install poetry
        run: pip install poetry
      - name: Run tests
        run: tox -e test
